# Generated by Django 5.2.5 on 2025-09-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
