# Generated by Django 5.2.5 on 2025-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General Inquiry')], default='general', max_length=50),
        ),
    ]
